services:
  - type: web
    name: podcast-cleanup
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: R2_ENDPOINT
        sync: false
      - key: R2_ACCESS_KEY
        sync: false
      - key: R2_SECRET_KEY
        sync: false
    plan: free
    branch: main
    autoDeploy: true
